### Introduction

Support Vector Machine (SVM) is a supervised machine learning algorithm used for classification and regression tasks. It works by finding the best boundary that separates different categories of data. The boundary is selected to create the maximum margin between the categories. In this project, SVM is applied to the medical insurance dataset to classify insurance charges into high and low categories based on customer information such as age, BMI, smoking status, and other features.

In [1]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("insurance.csv")

# Display first five rows
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [2]:
# Check dataset dimensions
print("Dataset Shape:", df.shape)

# Check column names, data types, and non-null values
print("\nDataset Information:")
df.info()

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Display statistical summary
print("\nStatistical Summary:")
df.describe()

Dataset Shape: (1338, 7)

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

Missing Values:
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

Statistical Summary:

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

df.shape shows the number of rows and columns.



df.info() shows column names and data types.



df.isnull().sum() counts missing values in each column.



df.describe() shows statistics such as mean, minimum, and maximum.

**CREATING THE TARGET VARIABLE**

In [4]:
# Calculate median insurance charges
median_charges = df["charges"].median()

# Classify charges into high and low categories
df["high_charges"] = (df["charges"] > median_charges).astype(int)

# Display results
print("Median Charges:", median_charges)

print("\nTarget Variable Distribution:")
print(df["high_charges"].value_counts())

df.head()

Median Charges: 9382.033

Target Variable Distribution:
high_charges
1    669
0    669
Name: count, dtype: int64

   age     sex     bmi  children smoker     region      charges  high_charges
0   19  female  27.900         0    yes  southwest  16884.92400             1
1   18    male  33.770         1     no  southeast   1725.55230             0
2   28    male  33.000         3     no  southeast   4449.46200             0
3   33    male  22.705         0     no  northwest  21984.47061             1
4   32    male  28.880         0     no  northwest   3866.85520             0

Median: The middle value of insurance charges.



0 = Low charges: Charges less than or equal to the median.



1 = High charges: Charges greater than the median.



value_counts() counts how many records belong to each category.

**DEFINING X AND Y**

In [5]:
# Select input features
X = df.drop(["charges", "high_charges"], axis=1)

# Select target variable
y = df["high_charges"]

print("Input Features (X):")
print(X.head())

print("\nTarget Variable (y):")
print(y.head())

Input Features (X):
   age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

Target Variable (y):
0    1
1    0
2    0
3    1
4    0
Name: high_charges, dtype: int64